title: <p align="center"> Ngoc Nguyen </p>


logo: "/images/Ngoc-Nguyen.jpg?raw=true" 


description: 
  <p align="center">
  <a href="https://drive.google.com/file/d/1s2lfhAhQ1ssCa8xlsUK6hVD-YTSJ8UfZ/view">Resume</a> |
  <a href="https://www.linkedin.com/in/ngocnguyen1996/">LinkedIn</a> |
  <a href="https://github.com/ngocknguyen">GitHub</a>
  </p>
  
  
  <p align="left">
  Hi, this is Ngoc (Katie)!
  
  I'm currently a Data Analyst @ Infineon Technologies and a MS Candidate in Analytics @ GA Tech.  <br>
  I am passionate about solving real-world problems using data science!
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

