title: Ngoc Nguyen # your name (or website title) here

logo: "/images/_DSC8577.JPG" # your photo (or logo) here

description: 
  <p align="center">
  <a href="https://drive.google.com/file/d/13TJ3Qm5BmXSWZoY4Pn-aQZ6oplzyq-7I/view?usp=sharing">Resume</a> |
  <a href="https://www.linkedin.com/in/ngocnguyen1996/">LinkedIn</a> |
  <a href="https://github.com/ngocknguyen">GitHub</a>
  </p>
  Hi, I'm graduting soon from my BS in Business Analytics at SJSU (December 2021)
  <br><br>
  I am passionate about solving real-world problems using data science  
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

